# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ExtendTodo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ExtendTodo
  pod 'KeychainSwift'
end
